backend/admin_side/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'admin_side'
urlpatterns = [
    path('', AdminPanelView.as_view(), name='admin_panel'),

    path('admin_login', AdminLoginView.as_view(), name='admin_login'),
    path('logout/', LogoutView.as_view(), name='logout'),

    path('add_student/', StudentCreateView.as_view(), name='add_student'),
    path('delete_student/<int:pk>/', StudentDeleteView.as_view(), name='delete_student'), 
    path('edit_student/<int:pk>/', StudentUpdateView.as_view(), name='edit_student'),  

    path('book_status/<int:student_id>/', BookStatusView.as_view(), name='book_status'),
    path('add_book_record/<int:user_id>/', BookRecordCreateView.as_view(), name='add_book_record'),
    path('delete-book/<int:pk>/', BookDeleteView.as_view(), name='delete_book'),  
    path('edit-book/<int:pk>/', BookUpdateView.as_view(), name='edit_book'),  

    path('fees_status/<int:student_id>/', FeesStatusView.as_view(), name='fees_status'),    
    path('add_fees_record/<int:user_id>/', FeesRecordCreateView.as_view(), name='add_fees_record'),    
    path('delete-fees/<int:pk>/', FeesDeleteView.as_view(), name='delete_fees'),    
    path('edit-fees/<int:pk>/', FeesUpdateView.as_view(), name='edit_fees'),    

    path('staff-status/', StaffListView.as_view(), name='staff_status'),    
    path('staff-create/', CreateStaffUserView.as_view(), name='create_staff'),
    path('edit_staff/<int:pk>/', StaffUpdateView.as_view(), name='edit_staff'),
    path('delete-staff/<int:pk>/', StaffDeleteView.as_view(), name='delete_staff'),

    path('librarian-status/', LibrarianListView.as_view(), name='librarian_status'),    
    path('librarian-create/', CreateLibrarianUserView.as_view(), name='create_librarian'),
    path('edit_librarian/<int:pk>/', LibrarianUpdateView.as_view(), name='edit_librarian'),
    path('delete-librarian/<int:pk>/', LibrarianDeleteView.as_view(), name='delete_librarian'),



]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('librarian/', include('librarian_side.urls')),

    path('staff/', include('staff_side.urls')),
    path('', include('admin_side.urls')),
    
]

backend/admin_side/models.py
from django.contrib.auth.models import AbstractUser, Group
from django.db import models
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    ROLE_CHOICES = [
        ('admin', 'Admin'),
        ('student', 'Student'),
        ('Staff', 'Staff'),
        ('Librarian', 'Librarian'),
    ]

    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=100, blank=True, null=True)
    dob = models.DateField(null=True)
    student_class = models.CharField(max_length=100, null=True, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)

    def __str__(self):
        return self.name if self.name else self.username


class Fees(models.Model):
    FEES_STATUS_CHOICES = [
        ('Paid', 'Paid'),
        ('Unpaid', 'Unpaid'),
        ('Partially Paid', 'Partially Paid'),  # New status for partial payments
    ]

    PAYMENT_METHOD_CHOICES = [
        ('Cash', 'Cash'),
        ('Credit Card', 'Credit Card'),
        ('Bank Transfer', 'Bank Transfer'),
        ('Online Payment', 'Online Payment'),
    ]

    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='fee')
    fees_status = models.CharField(max_length=100, choices=FEES_STATUS_CHOICES, null=True)
    paid_date = models.DateField(null=True)
    payment_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    due_amount = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)  # New field for total amount due
    payment_method = models.CharField(max_length=20, choices=PAYMENT_METHOD_CHOICES, null=True, blank=True)

    def __str__(self):
        return f'{self.user} - {self.fees_status}'


class Books(models.Model):
    BOOK_STATUS_CHOICES = [
        ('Borrowed', 'Borrowed'),
        ('Returned', 'Returned'),
    ]

    id = models.BigAutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='book')
    title = models.CharField(max_length=100, null=True, blank=True)
    book_status = models.CharField(max_length=10, choices=BOOK_STATUS_CHOICES, null=True)
    borrow_date = models.DateField(null=True)
    return_date = models.DateField(null=True)

    def __str__(self):
        return f'{self.title} - {self.book_status}'

backend/admin_side/views.py
from django.views.generic import CreateView, DeleteView, TemplateView, DetailView, UpdateView,ListView
from django.views import View
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse_lazy
from django.views.decorators.cache import never_cache
from .models import *
from .forms import *
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.contrib.messages.views import SuccessMessageMixin
from django.http import Http404


# Create your views here.


# admin login.
@method_decorator(never_cache, name='dispatch')
class AdminLoginView(View):
    form_class = LoginForm
    template_name = 'admin_login.html'

    def get(self, request, *args, **kwargs):
        # If the user is already logged in as admin, redirect to the admin panel
        if request.user.is_authenticated and request.user.role == 'admin':
            return redirect('admin_side:admin_panel')
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            
            # Check if the user exists
            try:
                user = User.objects.get(username=username)
            except User.DoesNotExist:
                messages.error(request, 'Username does not exist')
                return render(request, self.template_name, {'form': form})

            # Authenticate the user
            user = authenticate(request, username=username, password=password)
            if user is not None:
                # Check if the user is an admin
                if user.role == 'admin' and user.is_superuser:
                    login(request, user)
                    return redirect('admin_side:admin_panel')
                else:
                    messages.error(request, 'You are not authorized as an admin')
            else:
                messages.error(request, 'Incorrect password')
        
        return render(request, self.template_name, {'form': form})
    

# logout view.
class LogoutView(View):
    def get(self, request):
        logout(request)
        request.session.flush()
        messages.success(request, "logged out succesfully")
        return redirect('admin_side:admin_login')


# admin panel.
@method_decorator(never_cache, name='dispatch')
class AdminPanelView(LoginRequiredMixin, ListView):
    model = User
    template_name = 'student/admin_panel.html'
    context_object_name = 'students'  

    def get_queryset(self):
        return User.objects.filter(role='student')
    

# edit the student details.
class StudentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    form_class = StudentForm
    template_name = 'student/edit_student.html'
    success_message = "Student updated successfully!"

    def get_success_url(self):
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:admin_panel')
        elif self.request.user.role == 'Staff':
            return reverse_lazy('staff_side:staff_panel')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user  
        return context
    

# delete the student.
class StudentDeleteView(LoginRequiredMixin, DeleteView):
    model = User

    def get_success_url(self):
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:admin_panel')
        elif self.request.user.role == 'Staff':
            return reverse_lazy('staff_side:staff_panel')
    

# create new student.
class StudentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = StudentForm
    template_name = 'student/add_student.html'
    success_message = "Student added successfully!"

    def get_success_url(self):
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:admin_panel')
        elif self.request.user.role == 'Staff':
            return reverse_lazy('staff_side:staff_panel')


# list the book history.
class BookStatusView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'library_history/book_status.html'
    context_object_name = 'student'

    def get_object(self):
        # Fetch the student object based on the student_id from the URL
        student_id = self.kwargs.get('student_id')
        print("tttttttttttttttttttt",student_id)
        return get_object_or_404(User, id=student_id)
    
    
# create the book record.
class BookRecordCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Books
    form_class = BookRecordForm
    template_name = 'library_history/add_book_record.html'
    success_message = "Book record added successfully!"

    def get_form_kwargs(self):
        # Pass the specific user_id to the form
        kwargs = super(BookRecordCreateView, self).get_form_kwargs()
        kwargs['user_id'] = self.kwargs.get('user_id')  # Get the user_id from the URL
        return kwargs

    def get_success_url(self):
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:book_status', kwargs={'student_id': self.kwargs.get('user_id')})
        elif self.request.user.role == 'Librarian':
            return reverse_lazy('librarian_side:librarian_book_status', kwargs={'student_id': self.kwargs.get('user_id')})
        

# delete the book record.
class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Books

    def get_success_url(self):
        # Get the user associated with the book record
        student_id = self.get_object().user.id
        
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:book_status', kwargs={'student_id': student_id})
        elif self.request.user.role == 'Librarian':
            return reverse_lazy('librarian_side:librarian_book_status', kwargs={'student_id': student_id})
        

# edit the book record.
class BookUpdateView(LoginRequiredMixin, UpdateView):
    model = Books
    form_class = BookRecordForm
    template_name = 'library_history/edit_book_record.html'
    
    def get_success_url(self):
        # Ensure the book object has a user associated with it
        if self.object.user:  
            student_id = self.object.user.id  
            if self.request.user.role == 'admin':
                return reverse_lazy('admin_side:book_status', kwargs={'student_id': student_id})
            elif self.request.user.role == 'Librarian':
                return reverse_lazy('librarian_side:librarian_book_status', kwargs={'student_id': student_id})
        else:
            # Handle the case where there is no user associated with the book
            return reverse_lazy('some_default_view')  # Replace with a default view if necessary

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user_id'] = self.object.user.id  # Pass the user ID for filtering
        return kwargs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student'] = self.object.user  # Ensure you use the correct relation
        return context
    

# list the fees record.
class FeesStatusView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'fee_history/fee_status.html'
    context_object_name = 'student'

    def get_object(self):
        # Fetch the student object based on the student_id from the URL
        student_id = self.kwargs.get('student_id')
        return get_object_or_404(User, id=student_id)
    

# create fees record.
class FeesRecordCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Fees
    form_class = FeesRecordForm
    template_name = 'fee_history/add_fee_record.html'
    success_message = "Fees record added successfully!"

    def get_form_kwargs(self):
        # Pass the specific user_id to the form
        kwargs = super(FeesRecordCreateView, self).get_form_kwargs()
        kwargs['user_id'] = self.kwargs.get('user_id')  # Get the user_id from the URL
        return kwargs

    def get_success_url(self):
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:fees_status', kwargs={'student_id': self.kwargs.get('user_id')})
        elif self.request.user.role == 'Staff':
            return reverse_lazy('staff_side:staff_fees_status', kwargs={'student_id': self.kwargs.get('user_id')})
    

# delete the fees record.
class FeesDeleteView(LoginRequiredMixin, DeleteView):
    model = Fees

    def get_success_url(self):
        # Get the user associated with the book record
        student_id = self.get_object().user.id
        
        # Check the user's role to determine the redirect URL
        if self.request.user.role == 'admin':
            return reverse_lazy('admin_side:fees_status', kwargs={'student_id': student_id})
        elif self.request.user.role == 'Staff':
            return reverse_lazy('staff_side:staff_fees_status', kwargs={'student_id': student_id}) 
    

# edit the fees record.
class FeesUpdateView(LoginRequiredMixin, UpdateView):
    model = Fees
    form_class = FeesRecordForm

backend/admin_side/templates/staff/create_staff.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Create New Staff</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Create Staff</button>
    </form>
</div> 
{% endblock content %}

backend/admin_side/templates/staff/edit_staff.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <h1 class="text-center mb-4">Edit Staff</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}  <!-- Render the form fields -->
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Update User</button>
            <a href="{% url 'admin_side:staff_status' %}" class="btn btn-secondary">Cancel</a>  <!-- Add a cancel button -->
        </div>
    </form>
</div>
{% endblock content %}

backend/admin_side/templates/staff/staff_list.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
<div class="content">
    {% if messages %}
    <div class="text-center">
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} text-center">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
    
    <div class="container-fluid mt-4">
        <h1 class="text-center mb-4">Staff Details</h1>
        
        <div class="row mb-3">
            <div class="col text-end">
                <a class="btn btn-primary" href="{% url 'admin_side:create_staff' %}">Create Staff</a>
            </div>
        </div>
        
        <div class="table-responsive"> <!-- Add responsiveness to the table -->
            <table class="table table-striped border">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">DOB</th>
                        <th scope="col">Email</th>
                        <th scope="col">Role</th>
                        <th scope="col">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for staff in staff_members %}  <!-- Loop through each book related to the student -->
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ staff.name }}</td>
                        <td>{{ staff.dob }}</td>
                        <td>{{ staff.email }}</td>
                        <td>{{ staff.role }}</td>
                        <td>
                            <a class="btn btn-link text-warning" href="{% url 'admin_side:edit_staff' staff.id %}">
                                <i class="fa-solid fa-pen-to-square"></i>
                            </a>
                            <button class="btn btn-link text-danger" data-bs-toggle="modal" data-bs-target="#confirmDeleteModal{{ staff.id }}">
                                <i class="fa-solid fa-trash"></i>
                            </button>

                            <!-- Confirmation Modal -->
                            <div class="modal fade" id="confirmDeleteModal{{ staff.id }}" tabindex="-1" aria-labelledby="confirmDeleteModalLabel{{ staff.id }}" aria-hidden="true">
                                <div class="modal-dialog">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="confirmDeleteModalLabel{{ staff.id }}">Confirm Deletion</h5>
                                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                        </div>
                                        <div class="modal-body">
                                            Are you sure you want to delete {{ staff.name }}?
                                        </div>
                                        <div class="modal-footer">
                                            <form action="{% url 'admin_side:delete_staff' staff.id %}" method="POST">
                                                {% csrf_token %}
                                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                                                <button type="submit" class="btn btn-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        
    </div>
</div>


{% endblock content %}